### ISSUE TITLE
Pimox 7.2-7 can't start VM

### ISSUE THREAD

**Issue by jimoyong** [pimox/pimox7#107]
Hi guys,
I installed pimox 7.2-7 successfully.
But can't start and install VMs, the VMs stop at 
![企业微信截图_16691931381605](https://user-images.githubusercontent.com/25045808/203504232-eaf515de-f8b2-4e5d-854f-8ca9be5b6acd.png)

Hardwares:
![企业微信截图_16691931245580](https://user-images.githubusercontent.com/25045808/203504352-1159bdd4-2a1b-4004-aaf0-1ff052a7ea52.png)

Options:
![企业微信截图_1669193150865](https://user-images.githubusercontent.com/25045808/203504401-94fdfa63-5db4-45a1-9f4c-a5a75e1ef0a4.png)

ISO:
![企业微信截图_16691931687275](https://user-images.githubusercontent.com/25045808/203504423-bef83b94-473e-4413-a0ba-a4e8add04f5b.png)

Does anyone get some ideas about my situations?
What should I do with it?
Thanks a lot!

**Comment by n8lauscher** [comment]
same configuration - same Problem - can´t boot any img,iso etc...

**Comment by diginfo** [comment]
me too, new install:

```
dpkg-statoverride: warning: --update given but /var/log/chrony does not exist
Created symlink /etc/systemd/system/chronyd.service → /lib/systemd/system/chrony.service.
Created symlink /etc/systemd/system/multi-user.target.wants/chrony.service → /lib/systemd/system/chrony.service.
Setting up linux-headers-5.10.0-19-common (5.10.149-2) ...
Setting up pve-manager (7.2-7) ...
Job for pvestatd.service failed because the control process exited with error code.
See "systemctl status pvestatd.service" and "journalctl -xe" for details.
dpkg: error processing package pve-manager (--configure):
 installed pve-manager package post-installation script subprocess returned error exit status 1
Setting up proxmox-archive-keyring (2.0) ...
dpkg: dependency problems prevent configuration of proxmox-ve:
 proxmox-ve depends on pve-manager; however:
  Package pve-manager is not configured yet.

dpkg: error processing package proxmox-ve (--configure):
 dependency problems - leaving unconfigured
```

```
sync_wait: 34 An error occurred in another process (expected sequence number 7)
__lxc_start: 2074 Failed to spawn container "100"
```

**Comment by bp0** [comment]
> Hi guys, I installed pimox 7.2-7 successfully. But can't start and install VMs, the VMs stop at ![企业微信截图_16691931381605](https://user-images.githubusercontent.com/25045808/203504232-eaf515de-f8b2-4e5d-854f-8ca9be5b6acd.png)

@jimoyong: Config looks right. If you press ESC at that screen, do you get the UEFI menu?

**Comment by diginfo** [comment]
Just tried again, even use the image that you tested with:
```
#########################################################################################################################################
# Tested with image from:														                                                                                                 #
# https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-11-08/2021-10-30-raspios-bullseye-arm64-lite.zip	 #
#########################################################################################################################################
```
pve-manager still fails to install & configure

```
Backing up lvm.conf before setting pve-manager specific settings..
'/etc/lvm/lvm.conf' -> '/etc/lvm/lvm.conf.bak'
Setting 'global_filter' in /etc/lvm/lvm.conf to prevent zvols from being scanned:
global_filter=["a|.*|"] => global_filter=["r|/dev/zd.*|"]
Job for pvestatd.service failed because the control process exited with error code.
See "systemctl status pvestatd.service" and "journalctl -xe" for details.
dpkg: error processing package pve-manager (--configure):
 installed pve-manager package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for mailcap (3.69) ...
Processing triggers for initramfs-tools (0.140) ...
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u4) ...
Processing triggers for rsyslog (8.2102.0-2+deb11u1) ...
Processing triggers for pve-ha-manager (3.3-4) ...
Errors were encountered while processing:
 pve-manager
E: Sub-process /usr/bin/dpkg returned an error code (1)
```


```
.......
Created symlink /etc/systemd/system/multi-user.target.wants/zfs.target → /lib/systemd/system/zfs.target.
zfs-import-scan.service is a disabled or a static unit, not starting it.
Job for zfs-load-module.service failed because the control process exited with error code.
See "systemctl status zfs-load-module.service" and "journalctl -xe" for details.
A dependency job for zfs-import-cache.service failed. See 'journalctl -xe' for details.
Processing triggers for dbus (1.12.20-2) ...
Processing triggers for initramfs-tools (0.140) ...
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u4) ...
Processing triggers for man-db (2.9.4-2) ...
Setting up zfs-zed (2.1.5-1~bpo11~rpt1) ...
Created symlink /etc/systemd/system/zed.service → /lib/systemd/system/zfs-zed.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-zed.service → /lib/systemd/system/zfs-zed.service.
Errors were encountered while processing:
 pve-manager
 proxmox-ve
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by bp0** [comment]
@diginfo You're not having the same problem as @jimoyong . My response was to the OP. 

@diginfo, the output you've provided isn't useful. We need to see the errors when it is trying to configure pve-manager. Let's see your `dkms status` and `apt-get install --fix-broken` output?

I remember I had a similar problem at install and it was fixed this way: (https://github.com/pimox/pimox7/issues/87#issuecomment-1236403022)
```apt install dpkg-dev raspberrypi-kernel-headers linux-image-generic```
But I don't know if that is your problem or not.

**Comment by diginfo** [comment]
Thanks, I am halfway thru testing a manual install, I did add the kernel headers but install also failed in a similar way.

Also notice the the O/S no longer uses /etc/network/interfaces now and saw some errors about that, I have modified /etc/dhcpcd.conf instead but it still failed.

```
# apt-get install --fix-broken
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 42 not upgraded.
3 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
apt-listchanges: Can't set locale; make sure $LC_* and $LANG are correct!
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.UTF-8",
	LC_CTYPE = "en_US.UTF-8",
	LC_TERMINAL = "iTerm2",
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Setting up ceph-dkms (0.0.2) ...
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Removing old ceph-dkms-0.0.2 DKMS files...
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

------------------------------
Deleting module version: 0.0.2
completely from the DKMS tree.
------------------------------
Done.
Loading new ceph-dkms-0.0.2 DKMS files...
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
It is likely that 5.15.61-v8+ belongs to a chroot's host
Building for 5.15.61-v8+ and 5.15.76-v8+
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Module build for kernel 5.15.61-v8+ was skipped since the
kernel headers for this kernel does not seem to be installed.
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Building initial module for 5.15.76-v8+
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Error! Bad return status for module build on kernel: 5.15.76-v8+ (aarch64)
Consult /var/lib/dkms/ceph-dkms/0.0.2/build/make.log for more information.
dpkg: error processing package ceph-dkms (--configure):
 installed ceph-dkms package post-installation script subprocess returned error exit status 10
Setting up pve-manager (7.2-7) ...
Job for pvestatd.service failed because the control process exited with error code.
See "systemctl status pvestatd.service" and "journalctl -xe" for details.
dpkg: error processing package pve-manager (--configure):
 installed pve-manager package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of proxmox-ve:
 proxmox-ve depends on pve-manager; however:
  Package pve-manager is not configured yet.
 proxmox-ve depends on ceph-dkms; however:
  Package ceph-dkms is not configured yet.

dpkg: error processing package proxmox-ve (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 ceph-dkms
 pve-manager
 proxmox-ve
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by bp0** [comment]
@diginfo, it does still use /etc/network/interfaces, managed by proxmox. vmbr0 should have a static IP assigned. Proxmox discourages using dhcp.
It also seems that the missing kernel headers preventing dkms from building modules is your installation problem. If the dpkg-dev headers solution didn't solve it for you, then you might try starting over and editing the install script as described here: https://youtu.be/g1FXZIvVkq4?t=301

**Comment by diginfo** [comment]
@bp0  - Thanks for helping but no luck I'm afraid:

```
apt update
apt -y install dpkg-dev raspberrypi-kernel-headers linux-image-generic
apt -y install zfs-dkms zfsutils-linux
```
**and at the end of zfs install:**

```
DKMS: install completed.
Setting up libzpool5linux (2.1.5-1~bpo11~rpt1) ...
Setting up zfsutils-linux (2.1.5-1~bpo11~rpt1) ...
modprobe: FATAL: Module zfs not found in directory /lib/modules/5.15.61-v8+
Created symlink /etc/systemd/system/zfs-import.target.wants/zfs-import-cache.service → /lib/systemd/system/zfs-import-cache.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-import.target → /lib/systemd/system/zfs-import.target.
Created symlink /etc/systemd/system/zfs-mount.service.wants/zfs-load-module.service → /lib/systemd/system/zfs-load-module.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-load-module.service → /lib/systemd/system/zfs-load-module.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-mount.service → /lib/systemd/system/zfs-mount.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-share.service → /lib/systemd/system/zfs-share.service.
Created symlink /etc/systemd/system/zfs-volumes.target.wants/zfs-volume-wait.service → /lib/systemd/system/zfs-volume-wait.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-volumes.target → /lib/systemd/system/zfs-volumes.target.
Created symlink /etc/systemd/system/multi-user.target.wants/zfs.target → /lib/systemd/system/zfs.target.
zfs-import-scan.service is a disabled or a static unit, not starting it.
Job for zfs-load-module.service failed because the control process exited with error code.
See "systemctl status zfs-load-module.service" and "journalctl -xe" for details.
A dependency job for zfs-import-cache.service failed. See 'journalctl -xe' for details.
Processing triggers for initramfs-tools (0.140) ...
ln: failed to create hard link '/boot/initrd.img-5.10.0-19-arm64.dpkg-bak' => '/boot/initrd.img-5.10.0-19-arm64': Operation not permitted
update-initramfs: Generating /boot/initrd.img-5.10.0-19-arm64
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u4) ...
Processing triggers for man-db (2.9.4-2) ...
Setting up zfs-zed (2.1.5-1~bpo11~rpt1) ...
Created symlink /etc/systemd/system/zed.service → /lib/systemd/system/zfs-zed.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-zed.service → /lib/systemd/system/zfs-zed.service.
```
and:

```
root@pimox:/home/pi# systemctl status zfs-zed.service
● zfs-zed.service - ZFS Event Daemon (zed)
     Loaded: loaded (/lib/systemd/system/zfs-zed.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
  Condition: start condition failed at Sun 2022-12-04 14:16:42 +08; 4min 55s ago
             └─ ConditionPathIsDirectory=/sys/module/zfs was not met
       Docs: man:zed(8)

Dec 04 14:16:42 pimox systemd[1]: Condition check resulted in ZFS Event Daemon (zed) being skipped.
```


Maybe someone else could try out this installation using today's binaries etc etc ?

**Comment by bp0** [comment]
@diginfo This morning I installed pimox7 on a Raspberry Pi 4, to try and replicate your problem, but everything worked as expected.
* I used the official Raspberry Pi Imager and the latest Lite arm64 image, 2022-09-22-raspios-bullseye-arm64-lite.img.xz. 
* I followed the "Interactive Automatic Installer" instructions in the pimox7 README exactly, without editing the script. 
* After it finished, I had a working pimox install, I could log in to the web interface and create a VM using the Debian arm64 netinst ISO, only changing hardware/options to make the virtual CD-ROM use SCSI instead of IDE.
* I did not have working ZFS or Ceph because of the DKMS missing headers problem. Running `apt install dpkg-dev raspberrypi-kernel-headers linux-image-generic` triggered those modules to build for the 5.15.76-v8+ kernel, and after `modprobe zfs`, ZFS was working.

**Comment by diginfo** [comment]
Thanks very much, got it working with:

```
## 221205
## ======

sudo -s
curl https://raw.githubusercontent.com/pimox/pimox7/master/RPiOS64-IA-Install.sh > RPiOS64-IA-Install.sh;
chmod +x RPiOS64-IA-Install.sh;
./RPiOS64-IA-Install.sh;

## Post Install
###############
sudo -s
apt -y upgrade
apt install -y dpkg-dev raspberrypi-kernel-headers linux-image-generic
reboot

## Images
#########
sudo -s
cd /var/lib/vz/template/cache
curl https://us.lxd.images.canonical.com/images/debian/bullseye/arm64/default/20221204_05:25/rootfs.tar.xz > deb_arm64_20221204.tar.xz
curl https://us.lxd.images.canonical.com/images/alpine/3.17/arm64/default/20221204_13:13/rootfs.tar.xz > alpine_arm64_20221204.tar.xz
curl https://us.lxd.images.canonical.com/images/archlinux/current/arm64/default/20221204_04:18/rootfs.tar.xz > arch_arm64_20221204.tar.xz
```

**Comment by jimoyong** [comment]
> > Hi guys, I installed pimox 7.2-7 successfully. But can't start and install VMs, the VMs stop at ![企业微信截图_16691931381605](https://user-images.githubusercontent.com/25045808/203504232-eaf515de-f8b2-4e5d-854f-8ca9be5b6acd.png)
> 
> @jimoyong: Config looks right. If you press ESC at that screen, do you get the UEFI menu?

@bp0 Thank you for your reply. I tried press esc with the button VNC provided and  can't get into UEFI menu.

**Comment by jiangcuo** [comment]
Hi , try ```qm set <vmid> -m virt,gic-version=host```

**Comment by jimoyong** [comment]
> 
Thank you for your reply.
I tried your cmd, but it gave the answer as the following pic:
![image](https://user-images.githubusercontent.com/25045808/208803567-f47f5432-92d8-4924-81b5-963a6e43fde8.png)
I also tried -m with -machine  with no luck.
![image](https://user-images.githubusercontent.com/25045808/208804033-a14a5c7e-8784-4760-968c-599095db0493.png)
 Do you have any idea about that? Thank you

**Comment by titogrima** [comment]
Hi 

I had same problem and I solved it with this configuration for display

![imagen](https://user-images.githubusercontent.com/10048312/208873359-a3cb5e7c-36c2-45c4-9099-2d8aba9396f7.png)


At least in a non-graphical environment

![imagen](https://user-images.githubusercontent.com/10048312/208873673-ccaa2b62-bdf3-4002-8f83-1f303d135aff.png)

Regards!!

**Comment by jimoyong** [comment]
> Hi
> 
> I had same problem and I solved it with this configuration for display
> 
> ![imagen](https://user-images.githubusercontent.com/10048312/208873359-a3cb5e7c-36c2-45c4-9099-2d8aba9396f7.png)
> 
> At least in a non-graphical environment
> 
> ![imagen](https://user-images.githubusercontent.com/10048312/208873673-ccaa2b62-bdf3-4002-8f83-1f303d135aff.png)
> 
> Regards!!
Thank you for your reply!
I tired your config, with no luck. T_T
![image](https://user-images.githubusercontent.com/25045808/209036325-b86a8e7b-83c6-4992-ad52-dd28960e75f7.png)
![image](https://user-images.githubusercontent.com/25045808/209036421-8dd56b60-af11-40d7-97a3-f95812529e54.png)

Thank you all the same!

**Comment by jiangcuo** [comment]
qm set vmid --args "-machine virt,gic-version=host"

**Comment by jimoyong** [comment]
> qm set vmid --args "-machine virt,gic-version=host"
It works!!
Thank you very much! 

By the way, can you tell me the meaning of gic-version with pimox? Thank you!
![image](https://user-images.githubusercontent.com/25045808/209489816-e6c5eac2-19dd-4e28-99d2-1ea33ac747bc.png)

**Comment by saviothecnic** [comment]
![PiMoxRaspberry](https://user-images.githubusercontent.com/6697807/211552545-3029a62c-3aea-4585-a332-33f08be4453f.jpg)

![VerificaRAW_PiMox](https://user-images.githubusercontent.com/6697807/211552582-1ee5d5f9-2cf8-4355-912b-bec02b3ca043.jpg)

![ConversioneRawOK](https://user-images.githubusercontent.com/6697807/211552593-ad7a2ad6-836c-4511-9b8c-801a8072295d.jpg)

Friends, I too have the same problem
I installed Pimox on a Raspberry PI4 8Gb Rad and 1TB SSD
and I would like to run multiple virtualized raspberry systems on them.
I tried to imprint as you can see from the screenshots
a raw of a disk of a physical raspberry
it sees and imports without problems
But then the VM won't start for me
How do I fix it and how should I care for the raspberry clone VM?

Thank you

**Comment by jimoyong** [comment]
> ![PiMoxRaspberry](https://user-images.githubusercontent.com/6697807/211552545-3029a62c-3aea-4585-a332-33f08be4453f.jpg)
> 
> ![VerificaRAW_PiMox](https://user-images.githubusercontent.com/6697807/211552582-1ee5d5f9-2cf8-4355-912b-bec02b3ca043.jpg)
> 
> ![ConversioneRawOK](https://user-images.githubusercontent.com/6697807/211552593-ad7a2ad6-836c-4511-9b8c-801a8072295d.jpg)
> 
> Friends, I too have the same problem I installed Pimox on a Raspberry PI4 8Gb Rad and 1TB SSD and I would like to run multiple virtualized raspberry systems on them. I tried to imprint as you can see from the screenshots a raw of a disk of a physical raspberry it sees and imports without problems But then the VM won't start for me How do I fix it and how should I care for the raspberry clone VM?
> 
> Thank you

I 'm not sure about your situation, in my case, I use: [qm set vmid --args "-machine virt,gic-version=host"] in the shell, maybe you can have a try.

**Comment by saviothecnic** [comment]
![immagine](https://user-images.githubusercontent.com/6697807/212083215-7f4e8cb9-ca0f-4479-9630-36ef1f3bb583.png)

Thanks, I tried your command and it gave me an error
But can you do me a favor you can try putting it on your PiMox
any rapsberry physical machine by importing its raw disk
and tell me if you part? Thank you

**Comment by jimoyong** [comment]
> ![immagine](https://user-images.githubusercontent.com/6697807/212083215-7f4e8cb9-ca0f-4479-9630-36ef1f3bb583.png)
> 
> Thanks, I tried your command and it gave me an error But can you do me a favor you can try putting it on your PiMox any rapsberry physical machine by importing its raw disk and tell me if you part? Thank you

Sorry, it's my my ambiguous words. The "vmid" in the command above is the id of your vm, in the pic it should be 100 or 185.

**Comment by saviothecnic** [comment]
Ok I tried with  qm set 100 --args "-machine virt,gic-version=host"
as in the photo below now I have no error but the VM still does not start :(
![immagine](https://user-images.githubusercontent.com/6697807/220762510-75236d58-01af-4f24-8ed8-2936b029a566.png)
